name: maurice
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  markdown: ^7.2.2
  mustache_template: ^2.0.0
  path: ^1.9.0
  slugify: ^2.0.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
