name: maurice
description: Maurice a static website generator made in Dart. Generates blogs or websites quickly
version: 0.0.2
repository: https://github.com/ClementBeal/maurice
issue_tracker: https://github.com/ClementBeal/maurice/issues

topics:
  - blog
  - static
  - generator
  - website

environment:
  sdk: ^3.3.4

executables:
  maurice: maurice

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  intl: ^0.19.0
  markdown: ^7.2.2
  mustache_template: ^2.0.0
  path: ^1.9.0
  slugify: ^2.0.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
